os: linux

script:
  - echo dummy

deploy:
  - provider: elasticbeanstalk
    region: "us-east-1"
    app: "BletchMAME Web"
    env: "BletchmameWeb-stage"
    bucket: elasticbeanstalk-us-east-1-629514250742
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(development)$

