name: Deploy
on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Check out    
      - name: Check out
        uses: actions/checkout@v3

      # Install Zola
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.2

    
      # Build with Zola
      - name: Build with Zola
        run: |
          if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
            zola build
          else
            zola build --base-url "https://stage.bletchmame.org"
          fi

      # Deploy to S3
      - name: Deploy to S3
        uses: reggionick/s3-deploy@v4
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          folder: public
          bucket: ${{ github.event_name == 'workflow_dispatch' && secrets.S3_BUCKET_PROD || secrets.S3_BUCKET_STAGE }}
          private: true
          bucket-region: us-east-1
          dist-id: ${{ github.event_name == 'workflow_dispatch' && secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD || secrets.CLOUDFRONT_DISTRIBUTION_ID_STAGE }}
          invalidation: /*



